name: build go
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    name: Build go binaries
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

        go-version:
          - stable
          - "" # empty string = read version from go.mod

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      ARTIFACT_SSG_GO: "ssg-go-bin-go${{ matrix.go-version }}_${{ matrix.os }}"
      ARTIFACT_SOYWEB: "soyweb-bin-go${{ matrix.go-version }}_${{ matrix.os }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: "0"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          go-version-file: "./ssg-go/go.mod"
          cache: false
          check-latest: true

      - name: Build ssg-go
        run: |
          cd ssg-go;
          echo "PWD: $pwd"
          mkdir -p $ARTIFACT_SSG_GO
          echo 'Building ssg-go/ssg'
          go build -o $ARTIFACT_SSG_GO/ssg ./cmd/ssg

      - name: Build soyweb
        run: |
          cd soyweb;
          echo "PWD: $pwd"
          mkdir -p $ARTIFACT_SOYWEB
          echo 'Building ssg-go/ssg'
          go build -o $ARTIFACT_SOYWEB/soyweb ./cmd/soyweb
          go build -o $ARTIFACT_SOYWEB/ssg-minifier ./cmd/ssg-minifier
          go build -o $ARTIFACT_SOYWEB/minifier ./cmd/minifier

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: build_result-go${{ matrix.go-version }}_${{ matrix.os }}
          path: |
            ssg-go/${{ env.ARTIFACT_SSG_GO }}
            soyweb/${{ env.ARTIFACT_SOYWEB }}

