on:
  release:
    types: [created]

  push:
    tags:
      - 'v*'
      - 'test-*'

name: Release ssg-go
jobs:
  generate:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ssg-go from flake
        run: 'nix build .#ssg-go'

      - name: Create directory for x86_64_linux
        run: |
          mkdir ./x86_64_linux
          echo "debug: check permission"
          ls -al ./result/bin;
          ls -al ./x86_64_linux
          cp -a ./result/bin ./x86_64_linux/

      - name: Zip built binaries for x86_64_linux
        run: |
          zip -r ssg-go.zip ./x86_64_linux

      - name: Build ssg-go for aarch64_darwin
        run:  'nix build .#ssg-go-aarch64_darwin'

      - name: Include binaries for aarch64_darwin
        run: |
          mkdir ./aarch46_darwin
          cp -a ./result/bin ./aarch64_darwin/
          zip -r ssg-go.zip ./aarch64_darwin

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./ssg-go.zip
          asset_name: ssg-go.zip
          asset_content_type: application/zip
